OpenDataNode/open-data-node#238 - use appropriate configuration for ldap from {mdb, hdb}. Because hdb was used by default in debian 7. mdb is used by default in debian 8.

diff --git a/src/deb/control/postinst b/src/deb/control/postinst
--- a/src/deb/control/postinst
+++ b/src/deb/control/postinst
@@ -17,6 +17,7 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+ACL_LDIF=/usr/share/odn-simple/ldap/acl.ldif
 
 create_user() {
   if ! id odn-cas > /dev/null 2>&1 ; then
@@ -96,8 +97,14 @@ generate_keystore() {
     echo "<< generate_keystore"
 } 
 
-set_ldap_evolveum() {
+set_acl() { 
+    echo ">> set_acl"
+    DB_TYPE="$1"
+    sed -i "s/\$DB_TYPE/$DB_TYPE/g"  $ACL_LDIF
+    echo "<< set_acl"
+}
 
+set_ldap_evolveum() {
     echo ">> set_ldap"
 
     chmod +x /usr/share/odn-cas/bin/ldapgenerate 
@@ -108,7 +115,7 @@ set_ldap_evolveum() {
 
     CONFIG=/etc/default/slapd
     LDAP_DB_PATH=/var/lib/ldap_odn
-
+    
     if [ ! -f  /etc/ldap/slapd.d/cn\=config/cn\=schema/cn\=\{4\}midpoint.ldif ]; then
         /usr/share/odn-cas/bin/slapdconf add-schema midpoint -rootPassword admin -f /etc/ldap/schema/midpoint.schema
         echo "schema has been created"
@@ -119,16 +126,27 @@ set_ldap_evolveum() {
         chown -R openldap:openldap $LDAP_DB_PATH
             
         TREE="dc=opendata,dc=org"
-
-        /usr/share/odn-cas/bin/slapdconf create-suffix $TREE --dbDir $LDAP_DB_PATH --rootPassword admin
+        LIST_DATABASE=`/usr/share/odn-cas/bin/slapdconf list-databases`
+    
+        if  echo ${LIST_DATABASE} | grep -q "}mdb "; then
+            echo "create mdb database"
+            /usr/share/odn-cas/bin/slapdconf create-suffix $TREE --dbDir $LDAP_DB_PATH --rootPassword admin --dbType mdb
+            set_acl mdb
+        elif echo ${LIST_DATABASE} | grep -q "}hdb "; then
+            echo "create hdb database"
+            /usr/share/odn-cas/bin/slapdconf create-suffix $TREE --dbDir $LDAP_DB_PATH --rootPassword admin
+            set_acl hdb
+        else
+            echo "ERROR: unknown slapd database"
+            exit 1
+        fi
 
         /usr/share/odn-cas/bin/slapdconf add-module sssvlv
         /usr/share/odn-cas/bin/slapdconf add-overlay $TREE sssvlv olcSssVlvConfig
-
         /usr/share/odn-cas/bin/ldapgenerate -D cn=admin,$TREE -w admin -i -s dc=opendata,dc=org
 
         ldapadd -Y EXTERNAL -H ldapi:/// -f /usr/share/odn-simple/ldap/admin.ldif
-        ldapmodify -Y EXTERNAL -H ldapi:/// -f /usr/share/odn-simple/ldap/acl.ldif     
+        ldapmodify -Y EXTERNAL -H ldapi:/// -f $ACL_LDIF  
         echo "ldap user for IDM created"    
        
     else
